# Generated by Django 4.2.6 on 2023-10-10 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='Enter description here', max_length=50)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
