# Generated by Django 4.2.6 on 2023-10-13 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=1, help_text='Item count'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='£50', max_digits=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, help_text='Enter description here (can be blank)', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Purchase date (can be blank)'),
        ),
    ]
