# Generated by Django 4.2.6 on 2023-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_count_item_price_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Enter description here (can be blank)', max_length=50),
        ),
    ]
